version: "3.8"
services:
  zura:
    build:
      context: ./django1
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
  react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: zura
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: MarkedOneDB
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:


