version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: zura
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: MarkedOneDB
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
